//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476_Dev3_Nadon_Marc_Andre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Login { get; set; }
        public byte[] Password { get; set; }
    }
}
